### PR TITLE
Add `woke` to tooling.md

### PR DESCRIPTION
**Pull request by caitlinelfring**
Hello Inclusive Naming Community! I emailed ws-community@inclusivenaming.org on July 22 and wanted to follow up via a PR here after reading the Slack message in https://inclusive-naming.slack.com/archives/C01KHU7SS68/p1626989815062000?thread_ts=1626989803.061900&cid=C01KHU7SS68. I would love to know how to get `woke` onto the demo schedule to have it included. Thanks in advance!

Original Email: 

> I am interested in including the tool I created and maintain, `woke` ([https://github.com/get-woke/woke](https://github.com/get-woke/woke)) on your tooling list. I believe I will need to demo the tool for the group, would you be able to let me know what steps I need to take to make this happen. Thank you in advance for your time and I'm very excited to see how this community has grown! Looking forward to being a part of it!

### CODE REVIEW

**Review by justaugustus — APPROVED** [review]
Looking forward to it, @caitlinelfring!

**Comment by markcmiller86** [comment]
Apologies for the late comment here but speaking with an *inclusive naming* hat on, the name of this tool, `get-woke`, is troublesome to me. Not for the same reason language like `master/slave` is troublesome but for a different reason. And, I would like to raise the question about the merits of advertising a tool by this name here.

IMHO, the inclusive naming initiative is about inclusiveness, not `woke`ness and all of the either positive or negative connotations (depending on one's leanings) that may come along with the term `woke`. I think if INI endorses tools, we should ensure that such tools adhere to the same inclusive naming practices we are here to promote and encourage.

**Comment by spotz** [comment]
I agree with Mark on this, I think the name of this tool and it's repo is an issue for our own project.

**Comment by richsalz** [comment]
Strongly agree with @markcmiller86 !

**Comment by caitlinelfring** [comment]
Thanks for the feedback. There is actually a story behind the name of the tool which resonates deeply with me and is well beyond the scope of this forum. It is unfortunate that the term "woke" has been co-opted for political reasons by people with varying agendas, but ultimately the history and roots of the word (as well as its historic use within the African-American community) are relevant to the underlying creation of the tool and I have absolutely zero intention of changing it to appease disingenuous actors. 

I've decided not to move forward and will no longer be demoing woke. I will open a PR to revert since it's already been merged. I wish you the best of luck with your project.

**Comment by markcmiller86** [comment]
@caitlinelfring ... I realize I neglected to mention in my original remarks here that the *functionality* the tool appears to provide seems to be very much in line with INI needs and goals. It appears to treat the problem similarly to a linter which is kinda sort how I was thinking about an inclusive language tool ought to behave.

The challenge is (and as your remarks above allude to) the term `woke` doesn't really describe what the tool is or does. That term likely means many different things to many different people and has also, as you said, been co-opted which compounds the problem of using `woke` to communicate the tool's purpose.

This is the Inclusive *naming* initiative (as an aside, we in the tech community exercise the [power to name](https://bssw.io/items/inclusive-naming-initiative) quite a lot) and among several basic principles, one is to select names that have a high likelihood of communicating purpose and meaning clearly (to even the non-expert).

Its understandable that changing the name of the tool may not be desireable. It is regrettable, however, that that also appears to mean we cannot benefit from a *demo* of the tool in which you share any experiences and insights you've had in its development and use.

**Comment by Nytelife26** [comment]
@caitlinelfring Nice to see you around here. Is there a particular reason you've decided to retract your decision, though? It'd be good to have someone passionate and interested on board.

In any case, apologies, and best of luck.

**Comment by lee0c** [comment]
By INI's own evaluation standards, the naming meets third order concerns (The term is unclear, uses metaphor, or a more precise word is available / The language is idiomatic, and understanding is limited to those in a particular culture or in-group) and *may* meet second order (The term is culturally appropriated - this one seems debatable, but I recognize I'm no expert here).

If "we should ensure that such tools adhere to the same inclusive naming practices we are here to promote and encourage" it may be prudent to have a firmer understanding of how, when, and to what degree INI is evaluating, and what linking a tool from the INI site says - is that endorsement, or primarily acknowledgment of a related project? If it includes some level of vetting, is that standardized anywhere and to what degree is it carried out (project naming? evaluating replacement dictionaries used by linters? docs review?) ?

There's some level of flexibility understood in much of the language evaluation and replacement recommendation I've read so far, and it seems less than fair to give this project a quick no without further understanding of context when much of what's been written is context- and situation- aware.

The project seems overall beneficial to guide interested viewers to. If there's concern about the name, maybe it could benefit from an accompanying blurb about why the name was chosen that clarifies intent and meaning.

**Comment by markcmiller86** [comment]
> By INI's own evaluation standards, the naming meets third order concerns (The term is unclear, uses metaphor, or a more precise word is available / The language is idiomatic, and understanding is limited to those in a particular culture or in-group) and _may_ meet second order (The term is culturally appropriated - this one seems debatable, but I recognize I'm no expert here).

@lee0c thank you for citing this verbiage...I wen't looking and couldn't find what I needed within our own standards and policies.

**Comment by markcmiller86** [comment]
> it seems less than fair to give this project a quick no without further understanding of context

I agree with this and feel badly my *original* remarks seem to have created that outcome.

I am open to suggestions for what further attemps ([other than those above](https://github.com/inclusivenaming/org/pull/73#issuecomment-890564136) I can make to remedy.

All that said, my original concern, however poorly I may have worded it, still stands.

**Comment by bachand** [comment]
> If there's concern about the name, maybe it could benefit from an accompanying blurb about why the name was chosen that clarifies intent and meaning.

👍

**Comment by KAth1277** [comment]
Hi all,

New to the discussion. 

My first thought on this is - the use of language is subjective. We will all encounter, probably more than once, language being used that to us creates a concern, but in the context of another person's world view may have a different meaning or message attached to it. And we may be the person using that language. Yes, it's ok for us to reach consensus on words that perhaps would be best to be replaced with other words, but creating a barrier for certain words and as a result prohibiting certain groups or people from engaging with us, creates a situation where we are no longer inclusive.

And therefore, our work is no longer inclusive, balanced, or based on consensus. 

So I would prefer that we be welcoming to all, and not use language to further push ourselves farther apart from each other.

**Pull request merged**
